spring:
  datasource:
    url: ${AHENTETI_BLOG_DATASOURCE_URL}
    username: ${AHENTETI_BLOG_DATASOURCE_USERNAME}
    password: ${AHENTETI_BLOG_DATASOURCE_PASSWORD}
####################################################
#      Uncomment the following properties to       #
#   generate the @Entity associated SQL scripts    #
####################################################
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation: 
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: target/create.sql
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${AHENTETI_BLOG_GITHUB_OAUTH2_CLIENT_ID}
            clientSecret: ${AHENTETI_BLOG_GITHUB_OAUTH2_CLIENT_SECRET}

logging:
  level:
    org:
      springframework: INFO