server:
  servlet:
    session:
      timeout: 60m

spring:
  datasource:
    url: ${AHENTETI_BLOG_DATASOURCE_URL}
    username: ${AHENTETI_BLOG_DATASOURCE_USERNAME}
    password: ${AHENTETI_BLOG_DATASOURCE_PASSWORD}
    driverClassName: ${AHENTETI_BLOG_DATASOURCE_DRIVER_CLASSNAME}
  jpa:
    database-platform: ${AHENTETI_BLOG_DATASOURCE_DATABASE_PLATFORM}
    properties:
      hibernate:
        # format_sql: true
        hbm2ddl:
          delimiter: ";"
      javax:
        persistence:
          schema-generation: 
            create-source: metadata
            scripts:
              action: create
              create-target: target/create.sql
    # show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${AHENTETI_BLOG_GITHUB_OAUTH2_CLIENT_ID}
            clientSecret: ${AHENTETI_BLOG_GITHUB_OAUTH2_CLIENT_SECRET}
          google:
            clientId: ${AHENTETI_BLOG_GOOGLE_OAUTH2_CLIENT_ID}
            clientSecret: ${AHENTETI_BLOG_GOOGLE_OAUTH2_CLIENT_SECRET}
            

